runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots.txt
  static_files: zotcourse/static/robots.txt
  upload: zotcourse/static/robots.txt
  secure: always

- url: /static
  static_dir: zotcourse/static
  secure: always

- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest

- name: lxml
  version: latest

env_variables:
  USE_MEMCACHE: true
