runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: zotcourse/static
  secure: always

- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest

- name: lxml
  version: latest

- name: ssl
  version: latest

env_variables:
  USE_MEMCACHE: true
